# config.py

BOT_TOKEN = '1098880961:AAH5wKe_HZxjjIX8iDHEqZgaIhXK7XYgQsU'

BOT_LINK = 'https://t.me/testing2030'
OWNER_LINK = 'https://t.me/testing2030'

ORDER_CHANNEL = -1001248666344
CUSTOMER_CHANNEL = -1001248666344
ITEMS_CHANNEL = -1001248666344

CMD_ADD = '/Add'
CMD_CANCEL = '/Cancel'
CMD_REGISTER = '/Register'

TXT_REGISTER_CUST = 'Register'
TXT_FINISH = 'Finish'
TXT_ADD = 'Add'
TXT_CANCEL = 'Cancel'
TXT_YES = 'Yes'
TXT_MAIN_MENU = 'Back to menu'
TXT_PROCESS_CANCELLED = 'Process canceled !!. Try again'
TXT_SET_USERNAME = 'Must set username under settings >> username'

# Order txt
TXT_SELECT_ITEMS = 'Select Item'
TXT_PREV_DETAILS = 'Use your current information?'
TXT_ORDER_INTRO = 'Here {} so we can give the maximum service. Please share the phone number below'
TXT_SEND_SELFIE = 'Current selfies must be sent'
TXT_HOME_DELIVERY = 'Home Delivery'
TXT_PICKUP = 'self collection'
TXT_ORDER_COLLECTION = 'You are beautiful today, please choose * shipping * or * collection? * '
TXT_ADDRESS = 'Full address should now be filled in (for example: Ben Yehuda 1 Tel Aviv)'
TXT_PICKUP_INTRO = 'You will have to pick up your item in the designated place'
TXT_QUANTITY = 'Quantity should now be selected, in stock {}.'
TXT_ADD_ITEM = 'Anything else for you?'
TXT_REMAINING_ITEMS = 'Only {} grams in stock. Please select the remaining quantity. '
TXT_REPORT_SHORTAGE = 'Please consider adding the amount of {}. Only {} items available'
TXT_INVALID_AMOUNT = 'Invalid quantity. Please enter a valid amount '
TXT_TIME_SOON = 'as fast as possible'
TXT_TIME_2HR = 'Up to 2 hours from order confirmation'
TXT_TIME_3HR = '3 hours from order confirmation'
TXT_TIME_COORDINATE = 'Match your arrival time'
TXT_TIME_INPUT = 'Please choose the arrival time of the messenger (10:00 - 00:00)'
TXT_ADD_COMMENT = 'We are almost done, order comments? (Surplus, advance coordination, etc.) '
TXT_NO_ORDER = 'You have not made any orders yet!'

# display
TXT_ORDER_DISP_LINE_1 = 'Thank you. Your order details are: \n\nVarieties: {}\nQuantity: {} \nPhone: {} \nOrder Type: {} '
TXT_LOCATION = '\nAddress: {}'
TXT_ORDER_DISP_LINE_2 = 'Total amount: {} \nTotal amount payable: {}'
TXT_ORDER_DISP_LINE_3 = 'Expected arrival time: {} \nResponse: {}'
TXT_ORDER_DISP_LINE_4 = '\n \nThe order is correct? Please note after confirmation you cannot change * yes * or * no * '
TXT_ORDER_DISP_LINE_5 = '\nApproved: {} \nPhone: {} \nHour: {} \n\n'
TXT_NEW_ORDER = '{} Place new order \n'
TXT_CONFIRM_DISP_1 = 'Item: {} \nQuantity: {}'
TXT_CONFIRM_DISP_2 = '\nUsername: @{} \nPhone Number: {} \nOrder Type: {}'

# customerHandler.py txt
TXT_CUST_WELCOME = 'Hello {} Welcome to Club Wide, to continue with the registration process, make sure you have your ID or driver\'s license'
TXT_CUST_NAME = 'Please enter your real full name'
TXT_SHARE_PHONE = 'Share your phone number'
TXT_ALREADY_REGISTERED = 'You are a registered user, please continue to order'
TXT_CUST_PHONE = 'Thanks, now, click the Share my phone button'
TXT_ID_NUMBER = 'Thank you, now you need to enter your Social Security number including a 9 digit review number'
TXT_ID_NUMBER_ERROR = 'Incorrect ID number, must be 9 digits in case 0 should not be added at first'
TXT_CUST_SELFIE = 'Thanks, selfie should now be sent along with a page with an up-to-date date and time at the time of verification'
TXT_ID_PHOTO = 'Thank you, now you need to send your photo ID + certificate or driver\'s license'
TXT_FB_LINK = 'Thanks, now you need to attach a link to your Facebook profile'
TXT_FB_LINK_ERROR = 'Invalid link, please attach a valid link back to profile> more> Copy profile link'
TXT_CUST_LOC = 'A little more and we\'re done, now you have to order the city you want to sample: Tel Aviv'
TXT_FNAME = 'First name:'
TXT_LNAME = 'Surname:'
TXT_LOC = 'City:'
TXT_ID = 'ID Number:'
TXT_FB = 'Facebook Profile:'
TXT_PHONE_NO = 'Phone Number:'
TXT_APPROVED = 'Authentication Status:'
TXT_CUST_CONFIRM = 'Thanks, if everything is fine please click * Register * or * Cancel *'
TXT_DISP_1 = 'New Customer \nTelegram Number: {}'
TXT_DISP_2 = '\nName: {} {} \nIdentity Number: {}'
TXT_DISP_3 = 'Facebook Profile: {} \nCity: {} \nPhone Number: {} \nUsername: @{}'
TXT_CONFIRM_CUSTOMER = 'Confirm Customer'
TXT_CONFIRM_TEXT = 'Authentication successfully sent, now you need to wait for a verification message, if no confirmation is given for up to two hours after sending the verification please contact customer service'

# itemHandler.py txt
TXT_PRODUCT_TYPE = 'Please register strain (Sative / Indica / Hybrid)'
TXT_PRODUCT_NAME_ERR = 'Product exists, please enter another product name'
TXT_PRODCUT_IMAGE = 'Enter product image now'
TXT_PRODUCT_DES = 'Please enter a description of the strain'
TXT_PRODUCT_QTT = 'Please enter product quantity'
TXT_PRODUCT_CLICK_ADD = 'Please click * Add * or * Cancel *'
TXT_NAME = 'Name:'
TXT_TYPE = 'Type:'
TXT_QTT = 'In Stock:'
TXT_DES = 'Description:'
TXT_ITEM_DISP_1 = 'Display: {} \n🍪Type: {} \nInformation: {}'
TXT_ITEM_DISP_2 = '\n\nQuantity: 💰Price \n3 grams: 300 \n5 grams: 450 \n10 grams: 850 \n15 grams: 1250'
TXT_PRODUCT_ADDED = 'Product successfully added on'

# review
TXT_PRODUCT_LIKES = '\n\nLikes: {} \nDon\'t like: {}'
TXT_POST_ITEM = 'Post on varieties channel'
TXT_SERVICE = u'Service \U0001F6A8'

# managerHandler.py txt
TXT_MANAGER_INTRO = 'Welcome to Management'
TXT_REMOVE_ADMIN = 'Delete Manager'
TXT_ADD_ADMIN = 'Add Manager'
TXT_SETTINGS_MENU = u'Settings \u2699\uFE0F'
TXT_MANAGER_ID = 'Please enter the manager ID number'
TXT_ADD_ADMIN_SUCCESS = '{} Successfully added as manager.'
TXT_SENT_TEXT = 'Added to manage please click start /start updating menu'
TXT_USER_ALREADY_ADMIN = 'The user is already set as administrator.'
TXT_USER_NOT_FOUND = 'User not found!.'
TXT_REMOVE_ADMIN_SUCCESS = '{} You deleted this manager.'
TXT_REMOVED_ADMIN_TEXT = 'Deleted from management please press /start to update menu'
TXT_FUCK_YOU = 'WTF!! Do you want to remove the owner ?? Screw You'

# productHandler.py txt
TXT_PRODUCT_INTRO = 'Welcome to Product Management'
TXT_ADD_ITEM_BTN = 'Add Product'
TXT_DELETE_ITEM = 'Delete Product'
TXT_EDIT_ITEM = 'Edit Product'
TXT_TURN_ON = 'Order ON'
TXT_TURN_OFF = 'Order OFF'
TXT_TURN_OFF_TXT = 'Oops we are closed, operating hours 10am - 11pm.'
TXT_TURN_ON_TXT = 'Open for orders until 11pm.'
TXT_SELECT_PRODUCT = 'Select Product'
TXT_TURN_OFF_ITEM = 'Shutdown'
TXT_TURN_ON_ITEM = 'active'
TXT_DELETE_ITEM_TXT = 'Delete ❌'
TXT_NO_PRODUCT = 'No Products'
TXT_PRODUCT_NAME = 'Enter Sample Product Name: Og Kush'
TXT_NO_ITEM = 'No {} in your store !! Enter another product name: Og Kush '
TXT_UPDATE_ITEMS = 'Please update product inventory, only {} remains in stock.'
TXT_ITEM_QTT = 'Inventory updated successfully.'
TXT_CONFIRM_ORDER = 'Confirm Order'
TXT_CONFIRMATION_TEXT = 'Your order has been sent, you will receive a confirmation message within the next few minutes.'

# settingsHandler.py txt
TXT_ORDER_OPTION = 'Order Option'
TXT_STATISTICS = 'Statistics'
TXT_REVIEWS = 'Reviews'
TXT_BLOCK_USERS = 'Block User'
TXT_MANAGER = 'Management >>'
TXT_STOP_BOT = 'turn off'
TXT_BROADCAST = 'Broadcast Message'
TXT_PRODUCT = 'Product >>'
TXT_SETTINGS_INTRO = 'Welcome to Settings'
TXT_DELETE_PRODUCT = 'Delete ❌'
TXT_SETTINGS_BLOCK = 'User Block'
TXT_SETT_NO_CUST = 'No users to block'
TXT_STATS_DISP_1 = 'Statistics System \nStart Clicks: {} \nCustomers: {}'
TXT_STATS_DISP_2 = '\nOrders: {} \nProducts: {}'
TXT_STATS_CANCELLED_ORDERS = 'Canceled Orders'
TXT_STATS_COMPLETED_ORDERS = 'Orders Received'
TXT_STATS_PENDING_ORDERS = 'Shipping Orders'
TXT_STATS_BEST_CUST = 'Best Customers'
TXT_BROADCAST_TO_USERS = 'Welcome to send a message, the message you will register and send to me I will send it back to all active users in the bot'
TXT_MESSAGE_SENT = 'Message sent'

# bot.py txt main menu
TXT_REGISTER = u'Register \U0001F5DD'
TXT_MY_ORDERS = u'My Orders \U0001F6D2'
TXT_WAIT_APPROVAL = u'Pending verification \U0001F46E'
TXT_ORDER = u'Order \U0001F6F5'
TXT_BLOCKED = 'Blocked, please contact customer service'
TXT_MORE = 'More >>'
TXT_ABOUT = u'About \U0001F947'
TXT_JOKE = u'Joke \U0001F605'
TXT_NEXT_JOKE = 'Next joke'
TXT_CHECK_DETAILS = u'Account Details \U0001F4B3'
TXT_INVITE = u'Invite friend \U0001F46B'
TXT_COMMUNITY = 'VIP Customer Community'
TXT_JOKE_INTRO = 'Here\'s your joke,'
TXT_NOT_REGISTERED = 'Must register!'
TXT_MAIN_WELCOME = 'Welcome to ClubWeedVIP\'s Grasshopper'
TXT_WELCOME_BACK = 'Have fun returning to us'
TXT_WELCOME_MAIN_MENU = 'Welcome to main menu'

# bot.py txt
TXT_FORWARD_LINK = 'Move link below \n\nhttps: //t.me/ClubWeedMenu'
TXT_JOKE_ERR = 'Joke cracking error'
TXT_APPROVE_PASS = 'Validation passed successfully, you can now order'
TXT_USER_APPROVED = 'User is happy !!!'
TXT_DELETE_CUST_TEXT = 'Deleted alert system.'
TXT_CUST_DELETED = 'Customer Deleted !!'
TXT_UNABLE_DELETE = 'Unable to delete user'
TXT_BLOCKED_CUST = 'Blocked, please contact customer service'
TXT_UNBLOCKED_CUST = 'Blocking released, you can now order'
TXT_ORDER_LIST = 'Canceled / completed order list'
TXT_ZERO_ORDERS = 'No orders sent.'
TXT_BEST_BUYER = '@{} is {} your best buyer with {} items'
TXT_CANCEL_FAIL = 'The order is approved. Contact @ClubWeedVIP for more information '
TXT_DELETE_ORDER = 'Delete from Database'
TXT_CANCELLED_ORDER_TEXT = '{} Cancel order \nProduct: {} \nQuantity: {}'
TXT_ORDER_CANCELLED = 'Order Canceled'
TXT_DELETED_FROM_STORE = 'Deleted from Store'
TXT_MESSENGER_ARRIVE = 'Courier below please drop down, thank you for choosing ClubWeedVIP'
TXT_15MIN_OUT = 'Some more and the messenger with you, estimated time 15 minutes'
TXT_30MIN_OUT = 'Envoy on the way, estimated time 30 minutes.'
TXT_45MIN_OUT = 'Estimated arrival time: 45 minutes.'
TXT_1HR_OUT = 'The messenger will arrive in about an hour.'
TXT_2HR_OUT = 'The messenger will arrive in two hours from now.'
TXT_3HR_OUT = 'The messenger will arrive in 3 hours from now.'
TXT_DELIVERED_TEXT_1 = 'Product: {} \nQuantity: {} \nTotal Payment: {}'
TXT_DELIVERED_TEXT_2 = '\n\nThe order was successfully delivered !!. Don\'t forget to write * review * and rate us'
TXT_DELIVERED_TEXT = 'Product Provided!'
TXT_ORDER_RECEIVED = '{} \n {} \n {} \n Invitation received successfully. Please be available the bot will send timelines until the messenger is down. '
TXT_NOW = 'Down'
TXT_MINUTE = 'minutes'
TXT_HR = 'Hour'
TXT_DELIVER = 'Finish'
TXT_ORDER_ALREADY_CONFIRMED = 'Your order has already been accepted !!'
TXT_ABOUT_TEXT = 'ClubWeedVIP \n\nv1.1.0'

# moreHandler.py txt
TXT_FEEDBACK_BTN = u'feedback \U0001F4E2'
TXT_HIST_BTN = 'History'
TXT_SAVED_BTN = 'Save'
TXT_MORE_INTRO = 'Welcome, here you can connect with the rest of the community'
TXT_MORE_DESCRIPTION = 'Help us improve our service, we will always be happy to review for the good and for the worse! \nPlease enter a review description'
TXT_RATE_QUALITY = 'The quality of goods must now be rated, 1 * lowest 10 highest *.'
TXT_RATE_SERVICE = 'The quality of service must now be rated, * 1 lowest 10 highest *.'
TXT_RATE_PRICE = '* The price should now be rated, * 1 lowest 10 highest.'
TXT_FEEDBACK_DISP_1 = 'Seller\'s Name: ClubWeedVIP ☺️ \nCustomer Name: {} \nDate: {} \nReview Number: {} \n\n'
TXT_FEEDBACK_DISP_2 = '☎️Description: {} \n🍀Quality: {} / 10 \n\nService: {} / 10 \n💰Price: {} / 10'
TXT_FEEDBACK_SENT = 'Review sent, thank you.' + u'\u263A'

